version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tonthepduybao-db
    environment:
      POSTGRES_DB: ttdbdb
      POSTGRES_USER: ttdbuser
      POSTGRES_PASSWORD: ctyduybao2k25!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
